src/Acme/BooksBundle/Entity/Book.php
<?php

namespace Acme\BooksBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * Book
 *
 * @ORM\Table()
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks
 * @Assert\Callback(methods={"isFileUploadedOrExists"})
 */
class Book
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255)
     */
    private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="cover", type="string", length=255, nullable=true)
     */
    private $cover;

    /**
     * @var string
     *
     * @ORM\Column(name="bookfile", type="string", length=255, nullable=true)
     */
    private $bookfile;

    /**
     * @var string
     *
     * @ORM\Column(name="bookfile_realname", type="string", length=255, nullable=true)
     */
    private $bookfile_realname;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateread", type="datetime")
     */
    private $dateread;

    /**
     * @var boolean
     *
     * @ORM\Column(name="downloadable", type="boolean")
     */
    private $downloadable;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updated_at;

    /**
     * @var string
     */
    private $cover_file;

    /**
     * @Assert\File(maxSize="5000000")
     */
    private $bookfile_file;

    /**
     * @var string
     */
    private $cover_temp;

    /**
     * @var string
     */
    private $bookfile_old;

    /**
     * Get id
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     * @param  string $title
     * @return Book
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set author
     * @param  string $author
     * @return Book
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set cover
     * @param  string $cover
     * @return Book
     */
    public function setCover($cover)
    {
        $this->cover = $cover;

        return $this;
    }

    /**
     * Get cover
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Set bookfile
     * @param  string $bookfile
     * @return Book
     */
    public function setBookfile($bookfile)
    {
        $this->bookfile = $bookfile;

        return $this;
    }

    /**
     * Get bookfile
     * @return string
     */
    public function getBookfile()
    {
        return $this->bookfile;
    }

    /**
     * @param  string $bookfile_realname
     * @return Book
     */
    public function setBookfileRealname($bookfile_realname)
    {
        $this->bookfile_realname = $bookfile_realname;

        return $this;
    }

    /**
     * @return string
     */
    public function getBookfileRealname()
    {
        return $this->bookfile_realname;
    }

    /**
     * @param  \DateTime $dateread
     * @return Book
     */
    public function setDateread(\DateTime $dateread)
    {
        $this->dateread = $dateread;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateread()
    {
        return $this->dateread;
    }

    /**
     * Set downloadable
     *
     * @param  boolean $downloadable
     * @return Book
     */
    public function setDownloadable($downloadable)
    {
        $this->downloadable = $downloadable;

        return $this;
    }

    /**
     * Get downloadable
     * @return boolean
     */
    public function getDownloadable()
    {
        return $this->downloadable;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setCoverFile(UploadedFile $file = null)
    {
        $this->cover_file = $file;
        if (isset($this->cover)) {
            $this->cover_temp = $this->cover;
            $this->cover = null;
        } else {
            $this->cover = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getCoverFile()
    {
        return $this->cover_file;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setBookfileFile(UploadedFile $file = null)
    {
        $this->bookfile_file = $file;
        if (isset($this->bookfile)) {
            $this->bookfile_old = $this->bookfile;
            $this->bookfile = null;
        } else {
            $this->bookfile = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getBookfileFile()
    {
        return $this->bookfile_file;
    }

    /**
     * @return string
     */
    public function getBookfileOld()
    {
        return $this->bookfile_old;
    }

    /**
     * @param $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @return string
     */
    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }

    /**
     * @return string
     */
    protected function getUploadDir()
    {
        return '/uploads/books';
    }

    /**
     * @param  string $file
     * @return string
     */
    protected function getFileWebPath($file)
    {
        $level[0] = substr($file, 0, 2);
        $level[1] = substr($file, 2, 2);
        $level[2] = substr($file, 4, 2);
        $path = $this->getUploadDir().'/'.implode('/', $level);

        return $path.'/';
    }

    /**
     * @param  string $file
     * @return string
     */
    protected function getFileAbsolutePath($file)
    {
        $level[0] = substr($file, 0, 2);
        $level[1] = substr($file, 2, 2);
        $level[2] = substr($file, 4, 2);
        $path = $this->getUploadRootDir().'/'.implode('/', $level);

        return $path.'/';
    }

    /**
     * @return string
     */
    public function getCoverWebPath()
    {
        if (!$this->cover) return null;
        return $this->getFileWebPath($this->cover) . $this->cover;
    }

    /**
     * @return string
     */
    public function getBookfileWebPath()
    {
        if (!$this->bookfile) return null;
        return $this->getFileWebPath($this->bookfile) . $this->bookfile;
    }

    /**
     * @return null|string
     */
    public function getCoverAbsolutePath()
    {
        if (!$this->cover) return null;
        return $this->getFileAbsolutePath($this->cover) . $this->cover;
    }

    /**
     * @return null|string
     */
    public function getBookfileAbsolutePath()
    {
        if (!$this->bookfile) return null;
        return $this->getFileAbsolutePath($this->bookfile) . $this->bookfile;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        $this->updated_at = new \DateTime();

        if (null !== $this->getCoverFile()) {
            $filename = md5(uniqid(mt_rand(), true));
            $this->cover = $filename.'.'.$this->getCoverFile()->guessExtension();
        }
        if (null !== $this->getBookfileFile()) {
            $filename = md5(uniqid(mt_rand(), true));
            $this->bookfile = $filename.'.'.$this->getBookfileFile()->guessExtension();
            $this->bookfile_realname = $this->getBookfileFile()->getClientOriginalName();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null !== $this->getBookfileFile()) {
            $this->getBookfileFile()->move($this->getFileAbsolutePath($this->bookfile), $this->bookfile);
            if (isset($this->bookfile_old)) {
                @unlink($this->getFileAbsolutePath($this->bookfile_old) . $this->bookfile_old);
                $this->bookfile_old = null;
            }
            $this->bookfile_file = null;
        }
        if (null !== $this->getCoverFile()) {
            $this->getCoverFile()->move($this->getFileAbsolutePath($this->cover), $this->cover);
            if (isset($this->cover_temp)) {
                @unlink($this->getFileAbsolutePath($this->cover_temp) . $this->cover_temp);
                $this->cover_temp = null;
            }
            $this->cover_file = null;
        }
    }

    /**
     * @param ExecutionContextInterface $context
     */
    public function isFileUploadedOrExists(ExecutionContextInterface $context)
    {
        if(null === $this->bookfile && null === $this->bookfile_file)
            $context->addViolationAt('bookfile_file', 'You have to choose a file', array(), null);
    }
}

src/Acme/BooksBundle/Controller/DefaultController.php
<?php

namespace Acme\BooksBundle\Controller;

use Acme\BooksBundle\Entity\Book;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Acme\BooksBundle\Form\Type\BookType;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        $user = $this->getUser();

        /** @var $em \Doctrine\Common\Persistence\ObjectManager */
        $em = $this->getDoctrine()->getManager();

        $last_modified = $em->createQuery('select max(p.updated_at) from AcmeBooksBundle:Book p')->getSingleScalarResult();
        $datetime = new \DateTime($last_modified);
        $count = $em->createQuery('select count(p.id) from AcmeBooksBundle:Book p')->getSingleScalarResult();
        $response = new Response();

        $response->setPrivate();
        $response->setCache(array(
            'last_modified' => $datetime,
            'max_age' => 86400,
            'etag' => md5(($user?'1':'0').$count.$datetime->format('U'))
        ));

        if ($response->isNotModified($request)) {
            return $response;
        }

        $query = $em->createQuery('select p from AcmeBooksBundle:Book p order by p.dateread desc');
        $books = $query->getResult();

        $response->setContent($this->renderView('AcmeBooksBundle:Default:index.html.twig', array('books' => $books)));

        return $response;
    }

    public function editAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        if ($id = $request->get('id')) {
            $book = $em->getRepository('AcmeBooksBundle:Book')->find($id);
            if (!$book) throw new NotFoundHttpException('Книга не найдена');
        } else
            $book = new Book();

        $form = $this->createForm(new BookType(), $book);

        $form->handleRequest($request);

        if ($form->isValid()) {
            /** @var Book $book */
            $book = $form->getData();

            if (!$form->get('use_cover')->getData()) $book->setCover(null);
            if (!$form->get('use_bookfile')->getData()) $book->setBookfile(null);

            $book->preUpload();
            $em->persist($book);
            $em->flush();

            return $this->redirect($this->generateUrl('acme_books_homepage'));
        }

        return $this->render('AcmeBooksBundle:Default:edit.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    public function downloadAction($id)
    {
        /** @var Book $book */
        $book = $this->getDoctrine()->getRepository('AcmeBooksBundle:Book')->find($id);
        if (!$book) {
            throw new NotFoundHttpException('Книга не найдена');
        }
        $file = new BinaryFileResponse($book->getBookfileAbsolutePath());
        $file->setContentDisposition(ResponseHeaderBag::DISPOSITION_INLINE, $book->getBookfileRealname(), uniqid());

        return $file;
    }

    public function deleteCoverAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Book $book */
        $book = $em->getRepository('AcmeBooksBundle:Book')->find($id);
        if (!$book) {
            throw new NotFoundHttpException('Книга не найдена');
        }
        if ($book->getCover()) {
            $book->setCover(null);
            $em->flush();

            $file = $book->getAbsolutePath().$book->getCover();
            if ($file && is_file($file)) unlink($file);
        }

        return $this->redirect($this->generateUrl('acme_books_edit', array('id' => $id)));
    }

    public function deleteBookfileAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Book $book */
        $book = $em->getRepository('AcmeBooksBundle:Book')->find($id);
        if (!$book) {
            throw new NotFoundHttpException('Книга не найдена');
        }
        if ($book->getBookfile()) {
            $book->setBookfile(null)->setBookfileRealname(null);
            $em->flush();

            $file = $book->getAbsolutePath().$book->getBookfile();
            if ($file && is_file($file)) unlink($file);
        }

        return $this->redirect($this->generateUrl('acme_books_edit', array('id' => $id)));
    }

    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Book $book */
        $book = $em->getRepository('AcmeBooksBundle:Book')->find($id);
        if (!$book) {
            throw new NotFoundHttpException('Книга не найдена');
        }

        $em->remove($book);
        $em->flush();

        return $this->redirect($this->generateUrl('acme_books_homepage'));
    }
}

src/Acme/BooksBundle/Resources/views/Default/edit.html.twig
{% extends "AcmeBooksBundle::layout.html.twig" %}
{% block body %}
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    <div>
        {{ form_row(form.title) }}
    </div>
    <div>
        {{ form_row(form.author) }}
    </div>
    <div>
        {{ form_row(form.cover_file) }}
    </div>
    {% if (form.vars.value.id and form.vars.value.cover) %}
        <div>
            {{ imageResize(form.vars.value.coverWebPath) }}
            <a href="#" class="imageToggle">удалить изображение</a>
        </div>
    {% endif %}
    <div>
        {{ form_row(form.bookfile_file) }}
    </div>
    {% if (form.vars.value.id and form.vars.value.bookfile) %}
        <div>
            <a href="{{ path('acme_books_download', {id: form.vars.value.id}) }}">download</a>
            <a href="#" class="fileToggle">удалить файл</a>
        </div>
    {% endif %}
    <div>
        {{ form_row(form.dateread) }}
    </div>
    <div>
        {{ form_row(form.downloadable) }}
    </div>
    <div>
        {{ form_widget(form.Submit) }}
        <a href="{{ path('acme_books_homepage') }}">назад</a>
    </div>
    {{ form_row(form.use_cover) }}
    {{ form_row(form.use_bookfile) }}
    {{ form_end(form) }}
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
    function imageToggle(event)
    {
        event.stopPropagation();
        var $link = jQuery(event.target);
        $link.parent('div').find('img').toggle();
        if ($link.parent('div').find('img:hidden').length) {
            $link.html('вернуть изображение');
            jQuery('#book_use_cover').val(0);
        } else {
            $link.html('удалить изображение');
            jQuery('#book_use_cover').val(1);
        }
    }

    function fileToggle(event)
    {
        event.stopPropagation();
        var $link = jQuery(event.target);
        $link.parent('div').find('a[class!=fileToggle]').toggle();
        if ($link.parent('div').find('a[class!=fileToggle]:hidden').length) {
            $link.html('вернуть файл');
            jQuery('#book_use_bookfile').val(0);
        } else {
            $link.html('удалить файл');
            jQuery('#book_use_bookfile').val(1);
        }
    }

    jQuery(document).ready(function() {
        jQuery('.imageToggle').bind('click', imageToggle);
        jQuery('.fileToggle').bind('click', fileToggle);
    });
</script>
{% endblock %}

src/Acme/BooksBundle/Resources/views/Default/index.html.twig
{% extends 'AcmeBooksBundle::layout.html.twig' %}
{% block body %}
    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <a href="{{ path('acme_books_create') }}">Добавить книгу</a><br/>
    {% endif %}
    {% block books %}
        <table>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Cover</th>
                <th></th>
                {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                    <th></th>
                {% endif %}
            </tr>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>
                        {% if (book.cover) %}
                            {{ imageResize(book.coverWebPath) }}
                        {% endif %}
                    </td>
                    <td>
                        {% if book.downloadable %}
                            <a href="{{ path('acme_books_download', {id: book.id}) }}">download</a>
                        {% endif %}
                    </td>
                    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                        <td>
                            <a href="{{ path('acme_books_edit', {id: book.id} ) }}">edit</a>
                            <form action="{{ path('acme_books_delete', {id: book.id} ) }}" method="post" style="display: inline-block;">
                                <input type="submit" value="удалить" onclick="return confirm('Удалить?');">
                            </form>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% endblock %}
{% endblock %}